---
# define apic-infra network
- type: replace
  path: /networks/-
  value:
     name: apic-infra
     type: manual
     subnets:
     - range: 169.254.0.0/16
       gateway: 169.254.0.1
       azs: [z1, z2, z3]
       cloud_properties:
          name: ((apic_dvs))/((apic_infra_portgroup))
